service: cardwall
image: srbaker/cardwall

servers:
  web:
    hosts:
      - 135.181.250.235
    labels:
      traefik.http.routers.cardwall_secure.entrypoints: websecure
      traefik.http.routers.cardwall_secure.rule: Host(`cardwall.srbaker.org`)
      traefik.http.routers.cardwall_secure.tls.certresolver: letsencrypt

registry:
  username: srbaker
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "steven@stevenrbaker.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
